[package]
name = "mlp"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
clap = { version = "4.5.55", features = ["derive"] }
cudarc = { version = "0.18.1", features = ["cuda-12080"]}
itertools = "0.14.0"
lazy_static = "1.5.0"
rand = "0.9.2"
rand_chacha = "0.9.0"
rand_distr = "0.5.1"
rayon = "1.11"
ruviz = "0.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
no-std-compat = { version = "0.4.1", optional = true, features = ["alloc"] }
half = { version = "2", optional = true, default-features = false, features = [
    "num-traits",
    "rand_distr",
] }
float8 = { version = "0.7.0", optional = true }
float4 = { version = "0.2.0", optional = true }
libloading = "0.9.0"

[features]
default = [
    "std",
    "cublas",
    "cublaslt",
    "curand",
    "driver",
    "runtime",
    "nvrtc",
    "fallback-dynamic-loading",
]

fallback-latest = []
cuda-version-from-build-system = []
cuda-11040 = []
cuda-11050 = []
cuda-11060 = []
cuda-11070 = []
cuda-11080 = []
cuda-12000 = []
cuda-12010 = []
cuda-12020 = []
cuda-12030 = []
cuda-12040 = []
cuda-12050 = []
cuda-12060 = []
cuda-12080 = []
cuda-12090 = []
cuda-13000 = []
cuda-13010 = []
cuda-13020 = []

fallback-dynamic-loading = []
dynamic-loading = []
dynamic-linking = []
static-linking = []

driver = []
nvrtc = []
cublas = ["driver"]
cublaslt = ["driver"]
runtime = ["driver"]
cudnn = ["driver"]
curand = ["driver"]
nccl = ["driver"]
cusparse = ["driver"]
cusolver = ["driver", "cublas", "cublaslt", "cusparse"]
cusolvermg = ["cusolver"]
cufile = ["driver"]
nvtx = ["driver"]
cupti = ["runtime", "driver"]
cutensor = ["driver"]
cufft = ["driver"]

std = []
no-std = ["no-std-compat/std"]
f16 = ["dep:half"]
f8 = ["dep:float8"]
f4 = ["dep:float4"]
