name: snakemake
# channels:
#   - conda-forge
#   - defaults
# dependencies:
#   - python=3.10
#   - numpy
#   - pandas
#   - scikit-learn
#   - shap
#   - xgboost
channels:
- conda-forge
- defaults
dependencies:
# - rust >=1.92.0,<1.93
# - cuda-nvrtc ==12.8.93
# - nvtop >=3.3.1,<4
- r-lme4 >=1.1_38,<2
# - r-devtools >=2.5.2,<3
- r-flexplot >=0.7.4,<0.8
- r-bglr >=1.1.4,<2
# - bfg >=1.15.0,<2
- r-r.utils >=2.13.0,<3
- r-doparallel >=1.0.17,<2
# - py-xgboost >=3.2.0,<4
# - shap >=0.51.0,<0.52
- r >=4.5,<4.6
- r-stringr >=1.5.0,<2
# - pandas >=3.0.3,<4
# - numpy >=2.4.6,<3
# - scikit-learn >=1.8.0,<2
# - lightgbm >=4.6.0,<5
- python=3.11
# - lightgbm>=4.4.0
- cuda-version=12.0  # Forces Conda to grab the GPU-enabled LightGBM
- pandas
- numpy
- scikit-learn
- shap
- pip
- cmake
- ninja
# - cuda-toolkit
- gcc_linux-64=11    # Explicitly pull an older, perfectly compatible C compiler
- gxx_linux-64=11    # Explicitly pull the compatible C++ compiler
# - rasterio >=1.5.0,<2/
