[workspace]
authors = ["jeffersonfparil <jeffersonparil@gmail.com>"]
channels = ["conda-forge"]
name = "mlp"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rust = ">=1.92.0,<1.93"
cuda-nvrtc = "==12.8.93"
nvtop = ">=3.3.1,<4"
r-lme4 = ">=1.1_38,<2"
r-devtools = ">=2.5.0,<3"
r-flexplot = ">=0.7.4,<0.8"
r-bglr = ">=1.1.4,<2"
bfg = ">=1.15.0,<2"
